stages:
    - build
    - package
    - test
    - deploy

variables:
    DOCKER_DRIVER: overlay2

job_build:
    image: openjdk:8-jdk-slim
    stage: build
    variables:
            GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    script:
        - export GRADLE_USER_HOME=`pwd`/.gradle
        - chmod +x ./gradlew
        - ./gradlew clean installDist run -P generatePdf=true
    artifacts:
        paths:
            - app/build/install
        expire_in: 1 week

job_package:
    image: docker:latest
    services:
        - docker:dind
    stage: package
    variables:
        IMAGE_PATH: "$DOCKER_REPO_URL/$CI_PROJECT_PATH"
        IMAGE_TAG_CI: "$DOCKER_REPO_URL/$CI_PROJECT_PATH:$CI_COMMIT_SHA"
        IMAGE_TAG_DEV: "$DOCKER_REPO_URL/$CI_PROJECT_PATH:latest"
    before_script:
        - docker login -u $DOCKER_REPO_USER -p $DOCKER_REPO_PASS $DOCKER_REPO_URL
    script:
        - docker build --pull -t $IMAGE_TAG_CI -t $IMAGE_TAG_DEV app
        - docker push $IMAGE_PATH
    only:
        - master

job_test:
    stage: test
    script:
        - echo Test phase

job_deploy_development:
    stage: deploy
    script:
        - echo Deploy to Development cluster
    only:
        - master

job_deploy_staging:
    stage: deploy
    script:
        - echo Deploy to Staging cluster
    when: manual
    only:
        - master

job_deploy_production:
    stage: deploy
    script:
        - echo Deploy to Production cluster
    when: manual
    only:
        - master