swagger: "2.0"

info:
  description: API References for VAP Notification Service
  version: 1.0.0
  title: VAP Notification Service API References

host: "localhost:25070"

basePath: "/"

schemes:
- http

tags:
- name: handlers
  description: Handler APIs
- name: notifications
  description: Notification APIs
- name: service
  description: Service APIs

paths:
  /handlers:
    get:
      tags:
      - handlers
      summary: Get supported event handlers
      produces:
      - application/json
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: "#/definitions/Handler"
        500:
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ApiError"
  
  /notifications:
    get:
      tags:
      - notifications
      summary: Get notifications
      produces:
      - application/json
      parameters:
      - name: userid
        in: query
        description: user ID
        type: string
      - name: eventtype
        in: query
        description: event type
        type: string
      - name: deliveryMethod
        in: query
        description: delivery method
        type: string
      - name: timefr
        in: query
        description: start time (seconds since epoch)
        type: integer
        format: int64
        required: true
      - name: timeto
        in: query
        description: end time (seconds since epoch)
        type: integer
        format: int64
        required: true
      - name: pindex
        in: query
        description: page index (zero-based)
        type: integer
        required: true
      - name: psize
        in: query
        description: page size
        type: integer
        required: true
      - name: sort
        in: query
        description: page sort order
        type: string
        enum: [asc, desc]
        required: true
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Notification"
        500:
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ApiError"
  
  /info:
    get:
      tags:
      - service
      summary: Get service information
      produces:
      - application/json
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/ServiceInfo"
        500:
          description: Internal Server Error
          schema:
            $ref: "#/definitions/ApiError"
  
definitions:
  ServiceInfo:
    type: object
    required:
    - name
    - version
    properties:
      name:
        type: string
        description: service name
      version:
        type: string
        description: service version

  Notification:
    type: object
    required:
    - event
    - recipient
    - time
    properties:
      event:
        $ref: "#/definitions/Event"
      recipient:
        $ref: "#/definitions/Recipient"
      time:
        type: integer
        format: int64
        description: notification time

  Event:
    type: object
    required:
    - id
    - sourceId
    - time
    - type
    properties:
      id:
        type: string
        description: event id
      sourceId:
        type: string
        description: event source id
      time:
        type: integer
        format: int64
        description: event time (seconds since epoch)
      type:
        type: string
        description: event type
      jsonData:
        type: string
        description: event JSON data
      binaryData:
        type: string
        format: byte
        description: event Base64-encoded binary data

  Handler:
    type: object
    required:
    - name
    - type
    - notified
    - enabled
    properties:
      name:
        type: string
        description: handler name
      type:
        type: string
        description: event type
      notified:
        type: boolean
        description: indicates whether events handled by this handler will be queued for notification
      enabled:
        type: boolean
        description: indicates whether the handler is enabled

  Recipient:
    type: object
    required:
      - userId
      - address
      - type
    properties:
      userId:
        type: string
        description: user ID
      address:
        type: string
        description: recipient address (varies based on type)
      type:
        type: string
        description: recipient type (same as delivery method)
  
  ApiError:
    type: object
    required:
      - key
      - statusCode
      - serviceName
      - message
      - time
    properties:
      key:
        type: string
        description: error key
      statusCode:
        type: integer
        description: HTTP status code
      serviceName:
        type: string
        description: original service name
      message:
        type: string
        description: error message
      time:
        type: integer
        format: int64
        description: error time (seconds since epoch)